name: 'k8s-deploy-action'
description: 'Bake with kustomize and deploy to k8s'
inputs:
  folder:
    description: 'Folder with the manifest to bake'
    required: true
  image:
    description: 'Contents to inject into env file'
    required: true
runs:
  using: "composite"
  steps:      
      - uses: azure/k8s-bake@v2.2
        with:
          renderEngine: "kustomize"
          kustomizationPath: ${{ input.folder }}
      - name: Get image digest
        id: image_digest
        run: |
          jsonMetadata=$(skopeo inspect docker://${{ inputs.image }})
          jsonMetadata="${jsonMetadata//'%'/'%25'}"
          jsonMetadata="${jsonMetadata//$'\n'/'%0A'}"
          jsonMetadata="${jsonMetadata//$'\r'/'%0D'}"
          echo "::set-output name=metadata::$jsonMetadata"
        shell: bash
      - name: Print digest
        run: |
          echo "${{ fromJson(steps.image_digest.outputs.metadata).Name }}@${{ fromJson(steps.image_digest.outputs.metadata).Digest }}"
        shell: bash
