name: 'k8s-deploy-action'
description: 'Bake with kustomize and deploy to k8s'
inputs:
  folder:
    description: 'Folder with the manifest to bake'
    required: true
  secrets:
    description: 'Contents to inject into env file'
    required: false
runs:
  using: "composite"
  steps:
      - name: Make ir-backend envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_IR_DATAWRAPPER_TOKEN: ${{ secrets.ABC }}
          envkey_azure-application-insights-instrumentation-key-dev: abc
          directory: "./${{inputs.folder}}"
          file_name: ${{inputs.folder}}.env.secret

      - name: output secrets
        run: |
          cat ${{inputs.folder}}/${{inputs.folder}}.env.secret
        shell: bash
