name: 'k8s-deploy-action'
description: 'Bake with kustomize and deploy to k8s'
inputs:
  folder:
    description: 'Folder with the manifest to bake'
    required: true
  image:
    description: 'Container Image'
    required: true
  dry_run:
    description: set to non-empty string to prevent real deployment
    required: false
    type: string
    default: ""
  kube_config:
    description: kubeconfig to use
    required: true
    type: string
runs:
  using: "composite"
  steps:
      - uses: Azure/k8s-set-context@v2
        with:
          kubeconfig: ${{ inputs.kube_config }}  
      - uses: azure/k8s-bake@v2.2
        id: bake
        with:
          renderEngine: "kustomize"
          kustomizationPath: ${{ inputs.folder }}
      - name: Get image digest
        id: image_digest
        run: |
          jsonMetadata=$(skopeo inspect docker://${{ inputs.image }})
          jsonMetadata="${jsonMetadata//'%'/'%25'}"
          jsonMetadata="${jsonMetadata//$'\n'/'%0A'}"
          jsonMetadata="${jsonMetadata//$'\r'/'%0D'}"
          echo "::set-output name=metadata::$jsonMetadata"
        shell: bash
      - name: Print digest
        run: |
          echo "${{ fromJson(steps.image_digest.outputs.metadata).Name }}@${{ fromJson(steps.image_digest.outputs.metadata).Digest }}"
        shell: bash

      - uses: Azure/k8s-deploy@v1
        if: ${{ inputs.dry_run != '' }}
        with:
          manifests: ${{ steps.bake.outputs.manifestsBundle }}
          images: |
            ${{ fromJson(steps.image_digest.outputs.metadata).Name }}@${{ fromJson(steps.image_digest.outputs.metadata).Digest }}

